languageCode = "en"
languageName = "English"
weight = 1
title = "Mara Dominguez"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
   logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
   name = "Mara Dominguez"
   image = "img/profile.jpg"
   headline = "CC'25 Computer Science"
   bio = "CC'25 Computer Science"
   links = [
     { email = "mailto:drd2145@columbia.edu" },
     { github = "https://github.com/ddmngz" },
     { linkedin = "https://linkedin.com/in/mara-dominguez-6451812a1" },
   ]
