# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 name = "about me"
 url = "/"
 weight = 40

[[main]]
  name = "my projects"
  pageRef = "projects"
  weight = 10

[[main]]
 name = "coursework"
 pageRef = "pages/coursework"
 weight = 20

[[main]]
  name = "resume"
  url = "/files/resume.pdf"
  weight = 30


[[main]]
  name = "course projects"
  parent = "my projects"
  url = "/projects/coursework"
  weight = 20
[[main]]
  name = "personal projects"
  parent = "my projects"
  pageRef = "/projects/personal"
  weight = 10


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


