[[main]]
name = "about me"
url = "/"
weight = 40

[[main]]
name = "experience"
pageRef = "pages/experience"
weight = 5

[[main]]
name = "my projects"
pageRef = "projects"
weight = 10

[[main]]
name = "coursework"
pageRef = "pages/coursework"
weight = 20

[[main]]
name = "resume"
url = "/files/resume.pdf"
weight = 30

[[main]]
name = "class projects"
parent = "my projects"
url = "/projects/class_projects"
weight = 20

[[main]]
name = "personal projects"
parent = "my projects"
pageRef = "/projects/personal"
weight = 10

[[main]]
name = "nyt connections generator"
url = "/connections"
